# -- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK b JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID LEFT JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 and MONTH(s.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY 1, 3 DESC
