-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(s.USER_ID)) AS USERS
FROM ONLINE_SALE s LEFT JOIN USER_INFO i ON s.USER_ID = i.USER_ID
WHERE i.GENDER is not NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
