# # -- 코드를 입력하세요
SELECT p.PRODUCT_ID, PRODUCT_NAME, p.PRICE * SUM(o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p RIGHT JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY p.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID

# SELECT *
# FROM FOOD_PRODUCT

# SELECT *
# FROM FOOD_ORDER