# -- 코드를 입력하세요
SELECT f.FLAVOR # , f.TOTAL_ORDER, j.TOTAL_ORDER , f.TOTAL_ORDER + j.TOTAL_ORDER 
FROM FIRST_HALF f JOIN (SELECT SHIPMENT_ID,FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) j ON f.FLAVOR = j.FLAVOR
# GROUP BY FLAVOR
ORDER BY f.TOTAL_ORDER + j.TOTAL_ORDER DESC
LIMIT 3

# SELECT SHIPMENT_ID,FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR