-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a LEFT JOIN PATIENT p ON a.PT_NO = p.PT_NO 
LEFT JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE a.APNT_CNCL_YN = 'N' and DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13' and a.MCDP_CD = 'CS'
ORDER BY a.APNT_YMD