-- 코드를 작성해주세요
SELECT e.EMP_NO, e.EMP_NAME,
    CASE 
        WHEN g.SCORE < 80 THEN 'C'
        WHEN g.SCORE < 90 THEN 'B'
        WHEN g.SCORE < 96 THEN 'A'
        ELSE 'S'
        END AS GRADE,
    CASE 
        WHEN g.SCORE < 80 THEN 0
        WHEN g.SCORE < 90 THEN e.SAL * 10 / 100
        WHEN g.SCORE < 96 THEN e.SAL * 15 / 100
        ELSE e.SAL * 20 / 100
        END AS BONUS
        
FROM HR_DEPARTMENT d JOIN HR_EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID 
JOIN 
(SELECT ee.EMP_NO, AVG(SCORE) AS SCORE
FROM HR_GRADE g JOIN HR_EMPLOYEES ee ON g.EMP_NO = ee.EMP_NO
GROUP BY EMP_NO) g ON e.EMP_NO = g.EMP_NO
GROUP BY e.EMP_NO
ORDER BY 1

# SELECT ee.EMP_NO, AVG(SCORE) AS SCORE
# FROM HR_GRADE g JOIN HR_EMPLOYEES ee ON g.EMP_NO = ee.EMP_NO
# GROUP BY EMP_NO

