-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (
    SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA d
    WHERE YEAR(e.DIFFERENTIATION_DATE) = YEAR(d.DIFFERENTIATION_DATE)
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA e
ORDER BY 1, 2

    # SELECT YEAR(DIFFERENTIATION_DATE), MAX(SIZE_OF_COLONY)
    # FROM ECOLI_DATA
    # GROUP BY YEAR(DIFFERENTIATION_DATE)