SELECT FILE_ID, FILE_EXT, FILE_NAME, f.BOARD_ID
FROM USED_GOODS_FILE f
JOIN USED_GOODS_BOARD b ON f.BOARD_ID = b.BOARD_ID
WHERE b.VIEWS = (SELECT MAX(VIEWS) 
                    FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC
