# -- 코드를 작성해주세요
# SELECT
#   CASE 
#     WHEN (SKILL_CODE & 256 > 0) and ( SKILL_CODE & 16 > 0 or SKILL_CODE & 2048 > 0 or SKILL_CODE & 8192 > 0 ) then 'A'
#     WHEN SKILL_CODE & 1024 > 0 then 'B'
#     WHEN SKILL_CODE & 16 > 0 or SKILL_CODE & 2048 > 0 or SKILL_CODE & 8192 > 0 then 'C'
#     END AS GRADE
# , ID, EMAIL
# FROM DEVELOPERS
# WHERE (SKILL_CODE & 256 > 0 and (SKILL_CODE & 16 > 0 or SKILL_CODE & 2048 > 0 or SKILL_CODE & 8192 > 0 )) or SKILL_CODE & 1024 > 0 
# or (SKILL_CODE & 16 > 0 or SKILL_CODE & 2048 > 0 or SKILL_CODE & 8192 > 0)
# ORDER BY 1, 2

SELECT GRADE, ID, EMAIL
FROM (
    SELECT
        CASE 
            WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0)
                 AND (D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0)
                 THEN 'A'
            WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0 THEN 'B'
            WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 'C'
        END AS GRADE,
        D.ID, 
        D.EMAIL
    FROM DEVELOPERS D
) AS SUB
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;